import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Raleway } from "next/font/google";


const raleway = Raleway({ subsets: ["latin"] });

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ 
  weight: '600',
  subsets: ['latin'] 
  })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={raleway.className} >{children}</body>
    </html>
  );
}
